<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muris Saab, Ghassan Seba">

<title>Group 6 Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Group_6_Final_Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group_6_Final_Project_files/libs/quarto-html/quarto.js"></script>
<script src="Group_6_Final_Project_files/libs/quarto-html/popper.min.js"></script>
<script src="Group_6_Final_Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Group_6_Final_Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="Group_6_Final_Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group_6_Final_Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Group_6_Final_Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Group_6_Final_Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Group_6_Final_Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group 6 Final Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muris Saab, Ghassan Seba </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="kidney-stone-prediction-based-on-urine-analysis" class="level2">
<h2 class="anchored" data-anchor-id="kidney-stone-prediction-based-on-urine-analysis">Kidney Stone Prediction based on Urine Analysis</h2>
<section id="import-packages" class="level3">
<h3 class="anchored" data-anchor-id="import-packages">Import Packages</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AppliedPredictiveModeling)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(outliers)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="read-in-csv-file" class="level3">
<h3 class="anchored" data-anchor-id="read-in-csv-file">Read in CSV File</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read CSV into data frame</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>kidney_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"kindey_stone_urine_analysis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h2>
<section id="initial-inspection" class="level3">
<h3 class="anchored" data-anchor-id="initial-inspection">Initial Inspection</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check first &amp; last five rows and dimensions of data frame</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(kidney_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79  7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kidney_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gravity   ph osmo cond urea calc target
1   1.021 4.91  725 14.0  443 2.45      0
2   1.017 5.74  577 20.0  296 4.49      0
3   1.008 7.20  321 14.9  101 2.36      0
4   1.011 5.51  408 12.6  224 2.15      0
5   1.005 6.52  187  7.5   91 1.16      0
6   1.020 5.27  668 25.3  252 3.34      0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(kidney_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   gravity   ph osmo cond urea  calc target
74   1.022 5.09  736 19.8  418  8.53      1
75   1.025 7.90  721 23.6  301  9.04      1
76   1.017 4.81  410 13.3  195  0.58      1
77   1.024 5.40  803 21.8  394  7.82      1
78   1.016 6.81  594 21.4  255 12.20      1
79   1.015 6.03  416 12.8  178  9.39      1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify data types</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(kidney_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   79 obs. of  7 variables:
 $ gravity: num  1.02 1.02 1.01 1.01 1 ...
 $ ph     : num  4.91 5.74 7.2 5.51 6.52 5.27 5.62 5.67 5.41 6.13 ...
 $ osmo   : int  725 577 321 408 187 668 461 1107 543 779 ...
 $ cond   : num  14 20 14.9 12.6 7.5 25.3 17.4 35.9 21.9 25.7 ...
 $ urea   : int  443 296 101 224 91 252 195 550 170 382 ...
 $ calc   : num  2.45 4.49 2.36 2.15 1.16 3.34 1.4 8.48 1.16 2.21 ...
 $ target : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
</section>
<section id="data-cleaning-univariate-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-univariate-analysis">Data Cleaning &amp; Univariate Analysis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>missing_data <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(kidney_data))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>missing_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<section id="create-boxplots" class="level4">
<h4 class="anchored" data-anchor-id="create-boxplots">Create Boxplots</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to create boxplots with mean points</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>create_boxplot <span class="ot">&lt;-</span> <span class="cf">function</span>(data, y_var, title, ylab) {</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  mean_val <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[y_var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes_string</span>(<span class="at">y =</span> y_var)) <span class="sc">+</span> </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"red"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span> </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_discrete</span>() <span class="sc">+</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">y =</span> ylab) <span class="sc">+</span> </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> mean_val),  </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">shape =</span> <span class="dv">16</span>,                       </span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">2</span>,                         </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(plot)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplots for each variable</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data, <span class="st">"gravity"</span>, <span class="st">"Urine Specific Gravity"</span>, <span class="st">"Gravity"</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data, <span class="st">"ph"</span>, <span class="st">"Urine pH"</span>, <span class="st">"pH"</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data, <span class="st">"osmo"</span>, <span class="st">"Urine Osmolarity (mOsm/L)"</span>, <span class="st">"Osmo"</span>)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data, <span class="st">"cond"</span>, <span class="st">"Urine Conductivity (mMho)"</span>, <span class="st">"Cond"</span>)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data, <span class="st">"urea"</span>, <span class="st">"Urine Urea Concentration (mmol/L)"</span>, <span class="st">"Urea"</span>)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data, <span class="st">"calc"</span>, <span class="st">"Urine Calcium Concentration (mmol/L)"</span>, <span class="st">"Calc"</span>)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange boxplots in a 3x2 matrix</span></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot1, plot2, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot3, plot4, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot5, plot6, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">1</span></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="further-investigate-outliers" class="level4">
<h4 class="anchored" data-anchor-id="further-investigate-outliers">Further investigate Outliers</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grubbs' test for single outlier</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>grubbs_test_ph <span class="ot">&lt;-</span> <span class="fu">grubbs.test</span>(kidney_data<span class="sc">$</span>ph, <span class="at">type =</span> <span class="dv">10</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>grubbs_test_calc <span class="ot">&lt;-</span> <span class="fu">grubbs.test</span>(kidney_data<span class="sc">$</span>calc, <span class="at">type =</span> <span class="dv">10</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print Grubbs' test results</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Grubbs' test for ph:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grubbs' test for ph:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(grubbs_test_ph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Grubbs test for one outlier

data:  kidney_data$ph
G = 2.63910, U = 0.90956, p-value = 0.2797
alternative hypothesis: highest value 7.94 is an outlier</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Grubbs' test for calc:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Grubbs' test for calc:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(grubbs_test_calc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Grubbs test for one outlier

data:  kidney_data$calc
G = 3.12910, U = 0.87286, p-value = 0.04969
alternative hypothesis: highest value 14.34 is an outlier</code></pre>
</div>
</div>
<p>The Grubbs’ test was used to identify potential outliers in the kidney data, specifically focusing on the highest values for pH and calcium concentration.</p>
<ul>
<li><p><strong>pH:</strong> The test suggests that the highest pH value (7.94) is likely <strong>not a true outlier</strong>. The p-value (0.28) is relatively high, meaning it’s fairly common to observe such a value if it actually belongs to the same population as the other pH measurements.</p></li>
<li><p><strong>Calcium Concentration:</strong> The test provides weak evidence for the highest value (14.34) being a potential outlier. The p-value (0.05) is lower than for pH, but it might not be statistically significant depending on the chosen threshold (commonly 0.05). This suggests there’s a <strong>chance</strong> this value could be an outlier, but more evidence is needed for a definitive conclusion. Factors like a larger sample size or additional investigation could help clarify this.</p></li>
</ul>
<p>In simpler terms, the tests don’t definitively prove whether the values are true outliers, but they assess the likelihood of them being outliers based on their extremeness compared to the rest of the data. The results suggest the high pH value is likely not an outlier, while the high calcium concentration might be one, but more evidence is needed for confirmation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate z-scores for a vector</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>calculate_z_scores <span class="ot">&lt;-</span> <span class="cf">function</span>(x) { (x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">/</span> <span class="fu">sd</span>(x)}</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the z-score threshold for outlier detection</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>z_score_threshold <span class="ot">&lt;-</span> <span class="fl">2.5</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate z-scores for pH &amp; calc</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>ph_z_scores <span class="ot">&lt;-</span> <span class="fu">calculate_z_scores</span>(kidney_data<span class="sc">$</span>ph)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>calc_z_scores <span class="ot">&lt;-</span> <span class="fu">calculate_z_scores</span>(kidney_data<span class="sc">$</span>calc)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify outliers based on z-scores</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>ph_outliers <span class="ot">&lt;-</span> kidney_data <span class="sc">%&gt;%</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">abs</span>(ph_z_scores) <span class="sc">&gt;</span> z_score_threshold) <span class="sc">%&gt;%</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ph)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>calc_outliers <span class="ot">&lt;-</span> kidney_data <span class="sc">%&gt;%</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">abs</span>(calc_z_scores) <span class="sc">&gt;</span> z_score_threshold) <span class="sc">%&gt;%</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(calc)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the outliers</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="co">#print(ph_outliers)</span></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="co">#print(calc_outliers)</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to apply Dixon's Q test if sample size is between 3 and 30</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>apply_dixons_q_test <span class="ot">&lt;-</span> <span class="cf">function</span>(data, column_name) {</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  column_data <span class="ot">&lt;-</span> data[[column_name]]</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  sample_size <span class="ot">&lt;-</span> <span class="fu">length</span>(column_data)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (sample_size <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">&amp;&amp;</span> sample_size <span class="sc">&lt;=</span> <span class="dv">30</span>) {</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>    result <span class="ot">&lt;-</span> <span class="fu">dixon.test</span>(column_data, <span class="at">opposite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(result)</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">paste</span>(<span class="st">"Sample size for"</span>, column_name, <span class="st">"is"</span>, sample_size, <span class="st">"which is outside the range of 3-30"</span>))</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Dixon's Q test on pH outliers</span></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>ph_test_results <span class="ot">&lt;-</span> <span class="fu">apply_dixons_q_test</span>(ph_outliers, <span class="st">"ph"</span>)</span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dixon's Q Test for pH Outliers:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dixon's Q Test for pH Outliers:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ph_test_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Dixon test for outliers

data:  column_data
Q = 0.5, p-value = 1
alternative hypothesis: lowest value 7.9 is an outlier</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Dixon's Q test on calc outliers</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>calc_test_results <span class="ot">&lt;-</span> <span class="fu">apply_dixons_q_test</span>(calc_outliers, <span class="st">"calc"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Dixon's Q Test for Calc Outliers:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dixon's Q Test for Calc Outliers:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(calc_test_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Dixon test for outliers

data:  column_data
Q = 0.19277, p-value = 0.3487
alternative hypothesis: lowest value 12.68 is an outlier</code></pre>
</div>
</div>
<p><strong>Dixon’s Q Test (for identified z-score outliers):</strong></p>
<p>This test was applied only to the potential outliers identified by z-scores (assuming they were true outliers). It assesses how extreme these potential outliers are compared to their nearest neighbors within the subset of potential outliers.</p>
<ul>
<li><p><strong>pH:</strong> The Dixon’s Q test result (p-value = 1) suggests that the potential outlier identified by z-scores (lowest value, 7.9) is likely <strong>not a true outlier</strong>. There’s a high probability it originates from the same population as the other pH measurements.</p></li>
<li><p><strong>Calcium Concentration:</strong> The test result (p-value = 0.3487) provides weak evidence for the potential outlier identified by z-scores (lowest value, 12.68) being a true outlier. The p-value is not statistically significant at common thresholds (e.g., 0.05). There’s a chance it could be an outlier, but more evidence is needed.</p></li>
</ul>
<p><strong>Overall:</strong></p>
<p>While z-scores identified potential outliers in calcium concentration, further analysis using Dixon’s Q test suggests these might not be true outliers. The pH measurements seem to have no outliers based on both methods. It’s important to consider the limitations of these methods, especially sample size requirements for Dixon’s Q test.</p>
</section>
<section id="create-histograms-to-investigate-distributions-further" class="level4">
<h4 class="anchored" data-anchor-id="create-histograms-to-investigate-distributions-further">Create Histograms to Investigate Distributions Further</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to create histograms with mean and median lines</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>create_histogram <span class="ot">&lt;-</span> <span class="cf">function</span>(data, x_var, title, xlab) {</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  mean_val <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[x_var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  median_val <span class="ot">&lt;-</span> <span class="fu">median</span>(data[[x_var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  hist <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes_string</span>(<span class="at">x =</span> x_var)) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span>  </span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_val, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> median_val, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">x =</span> xlab) <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(hist)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histograms for each variable</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>hist1 <span class="ot">&lt;-</span> <span class="fu">create_histogram</span>(kidney_data, <span class="st">"gravity"</span>, <span class="st">"Urine Specific Gravity"</span>, <span class="st">"Gravity"</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>hist2 <span class="ot">&lt;-</span> <span class="fu">create_histogram</span>(kidney_data, <span class="st">"ph"</span>, <span class="st">"Urine pH"</span>, <span class="st">"pH"</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>hist3 <span class="ot">&lt;-</span> <span class="fu">create_histogram</span>(kidney_data, <span class="st">"osmo"</span>, <span class="st">"Urine Osmolarity (mOsm/L)"</span>, <span class="st">"Osmo"</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>hist4 <span class="ot">&lt;-</span> <span class="fu">create_histogram</span>(kidney_data, <span class="st">"cond"</span>, <span class="st">"Urine Conductivity (mMho)"</span>, <span class="st">"Cond"</span>)</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>hist5 <span class="ot">&lt;-</span> <span class="fu">create_histogram</span>(kidney_data, <span class="st">"urea"</span>, <span class="st">"Urine Urea"</span>, <span class="st">"Urea"</span>)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>hist6 <span class="ot">&lt;-</span> <span class="fu">create_histogram</span>(kidney_data, <span class="st">"calc"</span>, <span class="st">"Urine Calcium"</span>, <span class="st">"Calc"</span>)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange histograms in a 3x2 matrix</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(hist1, hist2, <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(hist3, hist4, <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(hist5, hist6, <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">1</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary Statistics </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(kidney_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">kidney_data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">79</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gravity</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: left;">▆▆▇▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">ph</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.03</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">4.76</td>
<td style="text-align: right;">5.53</td>
<td style="text-align: right;">5.94</td>
<td style="text-align: right;">6.38</td>
<td style="text-align: right;">7.94</td>
<td style="text-align: left;">▃▇▅▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">osmo</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">612.85</td>
<td style="text-align: right;">237.51</td>
<td style="text-align: right;">187.00</td>
<td style="text-align: right;">413.00</td>
<td style="text-align: right;">594.00</td>
<td style="text-align: right;">792.00</td>
<td style="text-align: right;">1236.00</td>
<td style="text-align: left;">▆▇▇▆▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">cond</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20.81</td>
<td style="text-align: right;">7.94</td>
<td style="text-align: right;">5.10</td>
<td style="text-align: right;">14.15</td>
<td style="text-align: right;">21.40</td>
<td style="text-align: right;">26.55</td>
<td style="text-align: right;">38.00</td>
<td style="text-align: left;">▅▆▇▇▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">urea</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">266.41</td>
<td style="text-align: right;">131.25</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">160.00</td>
<td style="text-align: right;">260.00</td>
<td style="text-align: right;">372.00</td>
<td style="text-align: right;">620.00</td>
<td style="text-align: left;">▅▇▇▆▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">calc</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.14</td>
<td style="text-align: right;">3.26</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: right;">3.16</td>
<td style="text-align: right;">5.93</td>
<td style="text-align: right;">14.34</td>
<td style="text-align: left;">▇▅▃▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">target</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="scatter-plots---predictor-relationships" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plots---predictor-relationships">Scatter plots - Predictor Relationships</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the predictor variables</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>kidney_predictor_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gravity"</span>, <span class="st">"ph"</span>, <span class="st">"osmo"</span>, <span class="st">"cond"</span>, <span class="st">"urea"</span>, <span class="st">"calc"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the kidney_data dataframe using the predictor variables</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>kidney_predictor_data <span class="ot">=</span> kidney_data[kidney_predictor_vars]</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Run grid of pairwise scatter plots for preditor variables</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(kidney_predictor_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation-matrix---predictor-relationships" class="level3">
<h3 class="anchored" data-anchor-id="correlation-matrix---predictor-relationships">Correlation Matrix - Predictor Relationships</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlations for predictor variables:</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>kidney_correlations <span class="ot">&lt;-</span> <span class="fu">cor</span>(kidney_predictor_data)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the correlation matrix for kidney data</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(kidney_correlations, <span class="at">method =</span> <span class="st">'color'</span>, <span class="at">order =</span> <span class="st">'hclust'</span>, <span class="at">addCoef.col =</span> <span class="st">'black'</span>, <span class="at">tl.pos =</span> <span class="st">'d'</span>, <span class="at">cl.pos =</span> <span class="st">'r'</span>, <span class="at">col =</span> <span class="fu">COL2</span>(<span class="st">'PRGn'</span>), <span class="at">outline=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>kidney_correlations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           gravity          ph       osmo        cond       urea       calc
gravity  1.0000000 -0.25334018  0.8614657  0.55906435  0.8234770  0.5256987
ph      -0.2533402  1.00000000 -0.2388411 -0.09767955 -0.2755569 -0.1194878
osmo     0.8614657 -0.23884108  1.0000000  0.81277999  0.8711785  0.5229794
cond     0.5590643 -0.09767955  0.8127800  1.00000000  0.4954049  0.3510295
urea     0.8234770 -0.27555694  0.8711785  0.49540493  1.0000000  0.5023267
calc     0.5256987 -0.11948777  0.5229794  0.35102955  0.5023267  1.0000000</code></pre>
</div>
</div>
</section>
<section id="predictor-variable-correlation-with-target-variable" class="level3">
<h3 class="anchored" data-anchor-id="predictor-variable-correlation-with-target-variable">Predictor Variable Correlation with Target Variable</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation matrix</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(kidney_data)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract correlations with the target variable</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>cor_with_target <span class="ot">&lt;-</span> cor_matrix[, <span class="st">"target"</span>]</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frame for plotting</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>cor_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Variable =</span> <span class="fu">rownames</span>(cor_matrix), <span class="at">Correlation =</span> cor_with_target)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the row corresponding to 'target'</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>cor_df <span class="ot">&lt;-</span> cor_df[cor_df<span class="sc">$</span>Variable <span class="sc">!=</span> <span class="st">"target"</span>, ]</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Variable Correlation
gravity  gravity  0.41981830
ph            ph -0.11219117
osmo        osmo  0.23183399
cond        cond  0.05971726
urea        urea  0.25840246
calc        calc  0.53772808</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot correlation values with the target variable using a bar plot</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cor_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(Variable, <span class="sc">-</span>Correlation), <span class="at">y =</span> Correlation)) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"dodgerblue"</span>) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlation with the Target Variable"</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Predictor Variable"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Correlation"</span>) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="covariance-matrix---predictorresponse-relationships" class="level3">
<h3 class="anchored" data-anchor-id="covariance-matrix---predictorresponse-relationships">Covariance Matrix - Predictor/Response Relationships</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate covariance matrix</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>cov_matrix <span class="ot">&lt;-</span> <span class="fu">cov</span>(kidney_data)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print covariance matrix with rounded values</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(cov_matrix, <span class="at">digits =</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        gravity     ph     osmo    cond     urea   calc target
gravity    0.00   0.00     1.48    0.03     0.78   0.01   0.00
ph         0.00   0.52   -41.09   -0.56   -26.20  -0.28  -0.04
osmo       1.48 -41.09 56413.26 1532.60 27158.90 404.95  27.44
cond       0.03  -0.56  1532.60   63.03   516.23   9.09   0.24
urea       0.78 -26.20 27158.90  516.23 17227.76 214.94  16.90
calc       0.01  -0.28   404.95    9.09   214.94  10.63   0.87
target     0.00  -0.04    27.44    0.24    16.90   0.87   0.25</code></pre>
</div>
</div>
</section>
</section>
<section id="feature-engineering-based-using-eda-findings" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering-based-using-eda-findings">Feature Engineering Based Using EDA Findings</h2>
<section id="polynomial-features---features-that-did-not-show-strong-linear-relationship-with-target" class="level4">
<h4 class="anchored" data-anchor-id="polynomial-features---features-that-did-not-show-strong-linear-relationship-with-target">Polynomial Features - Features that did not show strong linear relationship with target</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy the original dataframe</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>kidney_data_expand <span class="ot">&lt;-</span> kidney_data</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add polynomial features to the new dataframe</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>ph_squared <span class="ot">&lt;-</span> kidney_data_expand<span class="sc">$</span>ph<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>ph_cubed <span class="ot">&lt;-</span> kidney_data_expand<span class="sc">$</span>ph<span class="sc">^</span><span class="dv">3</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>cond_squared <span class="ot">&lt;-</span> kidney_data_expand<span class="sc">$</span>cond<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>cond_cubed <span class="ot">&lt;-</span> kidney_data_expand<span class="sc">$</span>cond<span class="sc">^</span><span class="dv">3</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display new dataframe </span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kidney_data_expand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gravity   ph osmo cond urea calc target ph_squared ph_cubed cond_squared
1   1.021 4.91  725 14.0  443 2.45      0    24.1081 118.3708       196.00
2   1.017 5.74  577 20.0  296 4.49      0    32.9476 189.1192       400.00
3   1.008 7.20  321 14.9  101 2.36      0    51.8400 373.2480       222.01
4   1.011 5.51  408 12.6  224 2.15      0    30.3601 167.2842       158.76
5   1.005 6.52  187  7.5   91 1.16      0    42.5104 277.1678        56.25
6   1.020 5.27  668 25.3  252 3.34      0    27.7729 146.3632       640.09
  cond_cubed
1   2744.000
2   8000.000
3   3307.949
4   2000.376
5    421.875
6  16194.277</code></pre>
</div>
</div>
<p>In our kidney data analysis, feature engineering through polynomial features is a necessary step to capture complex relationships between the variables and the target variable, especially given the weak linear correlations observed in our preliminary data exploration. Here’s a detailed explanation tailored specifically to our dataset:</p>
<ol type="1">
<li><p><strong>Capturing Non-linear Relationships</strong>: The correlations between our variables, such as pH and conductivity, and the target are notably weak. For instance, pH has a negative correlation of -0.11219117, indicating only a slight inverse linear relationship with the target. However, the relationship between pH and kidney health can be non-linear, as pH levels might affect the body differently at different concentrations. By creating polynomial features like <code>ph_squared</code> and <code>ph_cubed</code>, we allow our model to consider these non-linear effects, potentially capturing a threshold effect or a more complex dependency which might not be evident through linear analysis alone.</p></li>
<li><p><strong>Enhancing Predictive Accuracy</strong>: Our dataset includes variables like conductivity, which has a very low correlation (0.05971726) with the target. Squaring or cubing these features provides a more nuanced view of how they influence the target variable, possibly revealing hidden patterns that a simple linear model might miss. For instance, the effect of conductivity on the target might increase exponentially after a certain threshold, a relationship better modeled by polynomial features. By including these transformed features, our model can make more accurate predictions, particularly in a complex domain like medical diagnostics where interactions between variables are common.</p></li>
<li><p><strong>Domain-specific Relevance</strong>: In the context of predicting kidney health issues such as the formation of calcium oxalate crystals, understanding the nuanced effects of each variable is crucial. For example, the relationship between calcium concentration and kidney health is particularly critical. Calcium showed a relatively higher correlation (0.53772808) with the target, suggesting it has a more direct relationship. However, modeling its interaction with other variables like pH or urea through polynomial features could provide deeper insights into how combinations of these factors influence kidney health. Given the medical importance of accurately predicting health outcomes, these polynomial transformations are not just statistically beneficial but could be clinically significant.</p></li>
</ol>
</section>
<section id="aggregate-features---based-on-biological-relevance" class="level4">
<h4 class="anchored" data-anchor-id="aggregate-features---based-on-biological-relevance">Aggregate Features - Based on Biological Relevance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize features in the expanded dataset</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_osmo <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>osmo, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_cond <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>cond, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_calc <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>calc, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_ph <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>ph, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean aggregates</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>mean_agg_osmo_cond <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(kidney_data_expand[, <span class="fu">c</span>(<span class="st">"norm_osmo"</span>, <span class="st">"norm_cond"</span>)], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>mean_agg_calc_ph <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(kidney_data_expand[, <span class="fu">c</span>(<span class="st">"norm_calc"</span>, <span class="st">"norm_ph"</span>)], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate max aggregates</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>max_agg_osmo_cond <span class="ot">&lt;-</span> <span class="fu">pmax</span>(kidney_data_expand<span class="sc">$</span>norm_osmo, kidney_data_expand<span class="sc">$</span>norm_cond, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>max_agg_calc_ph <span class="ot">&lt;-</span> <span class="fu">pmax</span>(kidney_data_expand<span class="sc">$</span>norm_calc, kidney_data_expand<span class="sc">$</span>norm_ph, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="co"># List of normalized features to remove</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>norm_features <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"norm_osmo"</span>, <span class="st">"norm_cond"</span>, <span class="st">"norm_calc"</span>, <span class="st">"norm_ph"</span>)</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the normalized features from the dataframe</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>kidney_data_expand <span class="ot">&lt;-</span> kidney_data_expand[, <span class="sc">!</span>(<span class="fu">names</span>(kidney_data_expand) <span class="sc">%in%</span> norm_features)]</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the head of the modified dataframe to check the new features</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kidney_data_expand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gravity   ph osmo cond urea calc target ph_squared ph_cubed cond_squared
1   1.021 4.91  725 14.0  443 2.45      0    24.1081 118.3708       196.00
2   1.017 5.74  577 20.0  296 4.49      0    32.9476 189.1192       400.00
3   1.008 7.20  321 14.9  101 2.36      0    51.8400 373.2480       222.01
4   1.011 5.51  408 12.6  224 2.15      0    30.3601 167.2842       158.76
5   1.005 6.52  187  7.5   91 1.16      0    42.5104 277.1678        56.25
6   1.020 5.27  668 25.3  252 3.34      0    27.7729 146.3632       640.09
  cond_cubed mean_agg_osmo_cond mean_agg_calc_ph max_agg_osmo_cond
1   2744.000         -0.1930482       -1.0311472         0.4721892
2   8000.000         -0.1267262       -0.1453073        -0.1025223
3   3307.949         -0.9868394        0.5358705        -0.7449211
4   2000.376         -0.9485475       -0.6629698        -0.8624647
5    421.875         -1.7349812       -0.1175898        -1.6770291
6  16194.277          0.3986363       -0.6461329         0.5650686
  max_agg_calc_ph
1      -0.5180861
2       0.1076709
3       1.6174341
4      -0.6101092
5       0.6786058
6      -0.2450843</code></pre>
</div>
</div>
<p>Since <code>osmolarity</code> and <code>conductivity</code> are both related to the concentration of molecules and ions in the solution, these features might interact in ways that affect the formation of crystals. An aggregate measure of these two could provide insight into the overall ionic activity of the urine.</p>
<p>Since pH can affect the solubility of calcium compounds (and thus potentially influence the formation of calcium oxalate crystals), considering an interaction term between <code>calc</code> and <code>ph</code> might be informative.</p>
</section>
<section id="ratio-features---based-on-biological-relevance" class="level4">
<h4 class="anchored" data-anchor-id="ratio-features---based-on-biological-relevance">Ratio Features - Based on Biological Relevance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize urea and calcium in the expanded dataset</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_urea <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>urea, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_calc <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>calc, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_osmo <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>osmo, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>norm_cond <span class="ot">&lt;-</span> <span class="fu">scale</span>(kidney_data_expand<span class="sc">$</span>cond, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the normalized ratio of calcium to urea</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>calc_to_urea_ratio <span class="ot">&lt;-</span> kidney_data_expand<span class="sc">$</span>norm_calc <span class="sc">/</span> kidney_data_expand<span class="sc">$</span>norm_urea</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the normalized ratio of Osmolarity to Conductivity </span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>kidney_data_expand<span class="sc">$</span>osmo_to_cond_ratio <span class="ot">&lt;-</span> kidney_data_expand<span class="sc">$</span>norm_osmo <span class="sc">/</span> kidney_data_expand<span class="sc">$</span>norm_cond</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="co"># List of normalized features to remove</span></span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>norm_features <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"norm_urea"</span>, <span class="st">"norm_calc"</span>, <span class="st">"norm_osmo"</span>, <span class="st">"norm_cond"</span>)</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the normalized features from the dataframe</span></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>kidney_data_expand <span class="ot">&lt;-</span> kidney_data_expand[, <span class="sc">!</span>(<span class="fu">names</span>(kidney_data_expand) <span class="sc">%in%</span> norm_features)]</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows to verify the new columns</span></span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kidney_data_expand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  gravity   ph osmo cond urea calc target ph_squared ph_cubed cond_squared
1   1.021 4.91  725 14.0  443 2.45      0    24.1081 118.3708       196.00
2   1.017 5.74  577 20.0  296 4.49      0    32.9476 189.1192       400.00
3   1.008 7.20  321 14.9  101 2.36      0    51.8400 373.2480       222.01
4   1.011 5.51  408 12.6  224 2.15      0    30.3601 167.2842       158.76
5   1.005 6.52  187  7.5   91 1.16      0    42.5104 277.1678        56.25
6   1.020 5.27  668 25.3  252 3.34      0    27.7729 146.3632       640.09
  cond_cubed mean_agg_osmo_cond mean_agg_calc_ph max_agg_osmo_cond
1   2744.000         -0.1930482       -1.0311472         0.4721892
2   8000.000         -0.1267262       -0.1453073        -0.1025223
3   3307.949         -0.9868394        0.5358705        -0.7449211
4   2000.376         -0.9485475       -0.6629698        -0.8624647
5    421.875         -1.7349812       -0.1175898        -1.6770291
6  16194.277          0.3986363       -0.6461329         0.5650686
  max_agg_calc_ph calc_to_urea_ratio osmo_to_cond_ratio
1      -0.5180861         -0.3850686         -0.5501539
2       0.1076709          0.4775241          1.4721672
3       1.6174341          0.4330260          1.6495140
4      -0.6101092          1.8884445          0.8335970
5       0.6786058          0.6837801          1.0691128
6      -0.2450843          2.2331333          0.4109308</code></pre>
</div>
</div>
</section>
<section id="calcium-to-urea-ratio" class="level3">
<h3 class="anchored" data-anchor-id="calcium-to-urea-ratio">1. <strong>Calcium to Urea Ratio</strong></h3>
<p><strong>Why It’s Potentially Beneficial:</strong></p>
<ul>
<li><p><strong>Biological Interplay</strong>: Calcium and urea in the urine are crucial indicators of various metabolic and physiological processes. Calcium levels are directly relevant to kidney stone formation, particularly calcium oxalate stones, which are among the most common types. Urea concentration reflects the kidney’s function in excreting waste products derived from protein metabolism.</p></li>
<li><p><strong>Predictive of Crystal Formation</strong>: The balance between calcium and urea may influence the supersaturation and, consequently, the precipitation of calcium oxalate crystals. A higher ratio might indicate a relatively higher concentration of calcium compared to urea, potentially leading to a greater propensity for crystal formation.</p></li>
<li><p><strong>Normalization of Concentrations</strong>: Ratios normalize the concentrations against each other, adjusting for variations in urine concentration across samples. This can be particularly useful in studies where urine dilution varies significantly among samples.</p></li>
</ul>
</section>
<section id="osmolarity-to-conductivity-ratio" class="level3">
<h3 class="anchored" data-anchor-id="osmolarity-to-conductivity-ratio">2. <strong>Osmolarity to Conductivity Ratio</strong></h3>
<p><strong>Why It’s Potentially Beneficial:</strong></p>
<ul>
<li><p><strong>Reflects Ionic Balance</strong>: Osmolarity measures the total concentration of solute particles in solution, while conductivity measures the concentration of ions that contribute to the solution’s ability to conduct electricity. The ratio of osmolarity to conductivity provides insight into the balance between total solutes and those that are ionic—key for understanding the chemical environment conducive to stone formation.</p></li>
<li><p><strong>Indicator of Non-Ionic Solutes</strong>: This ratio can help distinguish between solute contributions from ionic and non-ionic compounds. For example, a high osmolarity with relatively low conductivity could suggest a higher proportion of non-ionic substances like urea or glucose in the urine.</p></li>
<li><p><strong>Diagnostic Utility</strong>: Such a ratio might help in diagnosing and understanding conditions like renal tubular acidosis, where the ability of the kidneys to manage acid-base balance (often reflected in ionic changes) is impaired.</p></li>
</ul>
</section>
</section>
<section id="explore-and-evaluate-new-features" class="level2">
<h2 class="anchored" data-anchor-id="explore-and-evaluate-new-features">Explore and Evaluate New Features</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to create boxplots with mean points</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>create_boxplot <span class="ot">&lt;-</span> <span class="cf">function</span>(data, y_var, title, ylab) {</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  mean_val <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[[y_var]], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes_string</span>(<span class="at">y =</span> y_var)) <span class="sc">+</span> </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"red"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span> </span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_discrete</span>() <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">y =</span> ylab) <span class="sc">+</span> </span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> mean_val),  </span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">shape =</span> <span class="dv">16</span>,                       </span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">2</span>,                         </span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(plot)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplots for each variable</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"gravity"</span>, <span class="st">"Urine Specific Gravity"</span>, <span class="st">"Gravity"</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"ph"</span>, <span class="st">"Urine pH"</span>, <span class="st">"pH"</span>)</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"osmo"</span>, <span class="st">"Urine Osmolarity (mOsm/L)"</span>, <span class="st">"Osmo"</span>)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"cond"</span>, <span class="st">"Urine Conductivity (mMho)"</span>, <span class="st">"Cond"</span>)</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>plot5 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"urea"</span>, <span class="st">"Urine Urea Concentration (mmol/L)"</span>, <span class="st">"Urea"</span>)</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>plot6 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"calc"</span>, <span class="st">"Urine Calcium Concentration (mmol/L)"</span>, <span class="st">"Calc"</span>)</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>plot7 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"ph_squared"</span>, <span class="st">"Polynomial Feature pH^squared"</span>, <span class="st">"pH Squared"</span>)</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>plot8 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"ph_cubed"</span>, <span class="st">"Polynomial Feature pH^cubed"</span>, <span class="st">"pH Cubed"</span>)</span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>plot9 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"cond_squared"</span>, <span class="st">"Polynomial Feature Conductivity^squared"</span>, <span class="st">"Cond Squared"</span>)</span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>plot10 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"cond_cubed"</span>, <span class="st">"Polynomial Feature Conductivity^cubed"</span>, <span class="st">"Cond Cubed"</span>)</span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>plot11 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"mean_agg_osmo_cond"</span>, <span class="st">"Mean Aggregate Osmolarity and Conductivity"</span>, <span class="st">"Mean Agg Osmo Cond"</span>)</span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>plot12 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"mean_agg_calc_ph"</span>, <span class="st">"Mean Aggregate Calcium and pH"</span>, <span class="st">"Mean Agg Calc pH"</span>)</span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>plot13 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"max_agg_osmo_cond"</span>, <span class="st">"Max Aggregate Osmolarity and Conductivity"</span>, <span class="st">"Max Agg Osmo Cond"</span>)</span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>plot14 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"max_agg_calc_ph"</span>, <span class="st">"Max Aggregate Calcium and pH"</span>, <span class="st">"Max Agg Calc pH"</span>)</span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a>plot15 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"calc_to_urea_ratio"</span>, <span class="st">"Calcium to Urea Ratio"</span>, <span class="st">"Calc to Urea Ratio"</span>)</span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a>plot16 <span class="ot">&lt;-</span> <span class="fu">create_boxplot</span>(kidney_data_expand, <span class="st">"osmo_to_cond_ratio"</span>, <span class="st">"Osmolarity to Conductivity Ratio"</span>, <span class="st">"Osmo to Cond Ratio"</span>)</span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange boxplots in a 8x2 matrix</span></span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(</span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot1, plot2, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot3, plot4, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot5, plot6, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot7, plot8, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot9, plot10, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot11, plot12, <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot13, plot14, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrangeGrob</span>(plot15, plot16, <span class="at">ncol =</span> <span class="dv">2</span>), </span>
<span id="cb47-48"><a href="#cb47-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">ncol =</span> <span class="dv">1</span></span>
<span id="cb47-49"><a href="#cb47-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="scatter-plots---expanded-predictor-relationships" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plots---expanded-predictor-relationships">Scatter plots - Expanded Predictor Relationships</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the predictor variables</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>kidney_predictor_expand <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gravity"</span>, <span class="st">"ph"</span>, <span class="st">"osmo"</span>, <span class="st">"cond"</span>, <span class="st">"urea"</span>, <span class="st">"calc"</span>,<span class="st">"ph_squared"</span>, <span class="st">"ph_cubed"</span>, <span class="st">"cond_squared"</span>, <span class="st">"cond_cubed"</span>, <span class="st">"mean_agg_osmo_cond"</span>, <span class="st">"mean_agg_calc_ph"</span>, <span class="st">"max_agg_osmo_cond"</span>, <span class="st">"max_agg_calc_ph"</span>, <span class="st">"calc_to_urea_ratio"</span>, <span class="st">"osmo_to_cond_ratio"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset the kidney_data dataframe using the predictor variables</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>kidney_predictor_data_expand <span class="ot">=</span> kidney_data_expand[kidney_predictor_expand]</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Run grid of pairwise scatter plots for preditor variables</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(kidney_predictor_data_expand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Group_6_Final_Project_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>